/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cjw_demo1_bspatch_BsPatch */

#ifndef _Included_com_cjw_demo1_bspatch_BsPatch
#define _Included_com_cjw_demo1_bspatch_BsPatch
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cjw_demo1_bspatch_BsPatch
 * Method:    patchFile
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_cjw_demo1_1bspatch_BsPatch_patchFile
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
